# -*- coding: utf-8 -*-
"""Modelo_Sarima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAFMXztN6AvkjVaC3_b2wtbi-jGTxS8R
"""

import os
import pickle
import json
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

warnings.filterwarnings("ignore")

# ======================================================
# URL DE GOOGLE SHEETS (definida a nivel global)
# ======================================================
SHEET_URL = "https://docs.google.com/spreadsheets/d/1x1FeUolFWlR07tgrc6F4cgeUhJYV7uQ5yuRTBHO8jWI/edit?gid=0#gid=0"

# ======================================================
# CONFIGURACIÓN DE CARPETA DE SALIDA SIMPLIFICADA
# ======================================================
def configurar_carpeta_salida():
    """Configura la carpeta donde se guardarán los resultados JSON"""
    try:
        # En Colab, guardar en Drive
        if 'IN_COLAB' in globals() and IN_COLAB:
            carpeta_base = "/content/drive/MyDrive/pronosticos"
        else:
            # En GitHub Actions o local
            carpeta_base = "./pronosticos"
        
        # Crear solo una carpeta
        os.makedirs(carpeta_base, exist_ok=True)
        print(f"✅ Carpeta creada/verificada: {carpeta_base}")
        
        return carpeta_base
    except Exception as e:
        print(f"⚠️  Error configurando carpeta: {e}")
        return None

# ======================================================
# 1. FUNCIÓN DE CONEXIÓN A GOOGLE SHEETS (COLAB + GITHUB)
# ======================================================


def conectar_a_google_sheets():
    """
    Conecta a Google Sheets de manera inteligente
    - En Colab: usa autenticación normal
    - En GitHub: puede usar Service Account
    """

    try:
        # Verificar si estamos en Google Colab
        try:
            from google.colab import auth

            IN_COLAB = True
        except:
            IN_COLAB = False

        if IN_COLAB:
            # ========== MODO COLAB ==========
            print("🔑 Autenticando en Google Colab...")

            # Autenticación interactiva
            auth.authenticate_user()
            from google.auth import default

            creds, _ = default()

            import gspread

            gc = gspread.authorize(creds)

        else:
            # ========== MODO GITHUB/LOCAL ==========
            import gspread

            # Intentar con variable de entorno (para GitHub Actions)
            creds_json = os.getenv("GOOGLE_SHEETS_CREDS")

            if creds_json:
                print("🔑 Usando Service Account desde variable de entorno...")
                from google.oauth2.service_account import Credentials

                creds_dict = json.loads(creds_json)
                scope = ["https://www.googleapis.com/auth/spreadsheets"]
                credentials = Credentials.from_service_account_info(
                    creds_dict, scopes=scope
                )
                gc = gspread.authorize(credentials)
            else:
                # Intentar autenticación normal (fallback)
                print("⚠️  Intentando autenticación normal...")
                gc = gspread.oauth()  # Esto abrirá navegador en local

        # Abrir la hoja
        spreadsheet = gc.open_by_url(SHEET_URL)
        worksheet = spreadsheet.get_worksheet(0)

        print("✅ Conexión exitosa a Google Sheets")
        return worksheet

    except Exception as e:
        print(f"❌ Error conectando a Google Sheets: {e}")
        print("⚠️  Usando datos de ejemplo para continuar...")
        return None


# ======================================================
# 2. CONFIGURACIÓN INICIAL DE COLAB
# ======================================================

# Montar Google Drive (solo funciona en Colab)
try:
    from google.colab import drive

    drive.mount("/content/drive", force_remount=False)
    IN_COLAB = True
    print("✅ Google Drive montado")

except:
    IN_COLAB = False
    print("⚠️  No es Google Colab, omitiendo montaje de Drive")

# ======================================================
# 3. INSTALAR DEPENDENCIAS (SOLO COLAB)
# ======================================================

if IN_COLAB:
    print("📦 Instalando dependencias en Colab...")
else:
    print("✅ En GitHub, las dependencias se instalan desde requirements.txt")

# ======================================================
# 4. IMPORTAR BIBLIOTECAS RESTANTES
# ======================================================

import gspread
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.dates as mdates

# Cargar jupyter-black (solo Colab)
if IN_COLAB:
    import jupyter_black

    jupyter_black.load()

# ======================================================
# 5. REEMPLAZAR LA IMPORTACIÓN DE 'direl_ts_tool_kit'
# ======================================================


def parse_datetime_index(df, date_column="date", format="%d/%m/%Y %H:%M:%S"):
    """
    Convierte una columna de fecha a datetime y la usa como índice
    (Reemplaza a la función de direl_ts_tool_kit)
    """
    df_copy = df.copy()
    df_copy[date_column] = pd.to_datetime(
        df_copy[date_column], format=format, errors="coerce"
    )
    df_copy.set_index(date_column, inplace=True)
    return df_copy


def plot_time_series(df, variable, units="", time_unit="Day"):
    """
    Grafica una serie de tiempo
    (Versión simplificada de la función original)
    """
    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(df.index, df[variable], linewidth=1)
    ax.set_title(f"Serie de Tiempo - {variable}")
    ax.set_xlabel(f"Tiempo ({time_unit})")
    ax.set_ylabel(f"{variable} {units}")
    ax.grid(True, alpha=0.3)

    # Formato de fechas
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d/%m %H:%M"))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45)

    plt.tight_layout()
    return fig


# ======================================================
# 6. CONECTAR Y CARGAR DATOS
# ======================================================

print("\n" + "=" * 60)
print("📥 CARGANDO DATOS DESDE GOOGLE SHEETS")
print("=" * 60)

# Conectar a Google Sheets
worksheet = conectar_a_google_sheets()

if worksheet is not None:
    # Obtener todos los datos
    datos = worksheet.get_all_values()

    # Convertir a DataFrame
    df0 = pd.DataFrame(datos[1:], columns=datos[0])

    print(f"✅ Datos cargados desde Google Sheets")
    print(f"📊 Dimensiones: {df0.shape[0]} filas × {df0.shape[1]} columnas")
    print(f"🔗 URL: {SHEET_URL}")

else:
    # ========== DATOS DE EJEMPLO (si falla la conexión) ==========
    print("📝 Usando datos de ejemplo para demostración...")

    # Crear datos de ejemplo simples
    import numpy as np

    fechas = pd.date_range(start="2024-01-01", periods=100, freq="H")

    datos_ejemplo = {
        "Date": [f.strftime("%d/%m/%Y %H:%M:%S") for f in fechas],
        "Temperature": 25 + 5 * np.sin(np.linspace(0, 10, 100)),
        "Humidity": 60 + 10 * np.cos(np.linspace(0, 8, 100)),
        "PM 2.5(µg/m³)": 20 + 8 * np.random.randn(100),
        "PM 10 (µg/m³)": 40 + 12 * np.random.randn(100),
        "PM 1.0 (µg/m³)": 10 + 4 * np.random.randn(100),
    }

    df0 = pd.DataFrame(datos_ejemplo)
    print(f"📊 Datos de ejemplo creados: {df0.shape[0]} filas")

print("\n📋 Primeras filas de datos:")
print(df0.head(2))

# ======================================================
# 6.1. VERIFICACIÓN DE ACTUALIZACIÓN DE DATOS
# ======================================================
print("\n📅 Verificando actualización de datos...")
print(f"Última fecha en datos: {df0['Date'].iloc[-1]}")
print(f"Total de registros: {len(df0)}")

# Verificar si hay datos recientes
try:
    ultima_fecha_str = df0['Date'].iloc[-1]
    ultima_fecha = pd.to_datetime(ultima_fecha_str, format="%d/%m/%Y %H:%M:%S", errors='coerce')
    if ultima_fecha:
        hoy = datetime.now()
        diferencia = hoy - ultima_fecha
        print(f"Días desde el último registro: {diferencia.days}")
        
        if diferencia.days > 7:
            print("⚠️  ADVERTENCIA: Los datos pueden estar desactualizados")
        else:
            print("✅ Datos actualizados recientemente")
except Exception as e:
    print(f"⚠️  Error verificando actualización: {e}")

df0.rename(
    columns={
        "Date": "date",
        "PM 1.0 (µg/m³)": "PM 1",
        "PM 2.5(µg/m³)": "PM 2.5",
        "PM 10 (µg/m³)": "PM 10",
    },
    inplace=True,
)

# ======================================================
# CONVERSIÓN DE DATOS Y LIMPIEZA
# ======================================================

print("🔍 Verificando tipos de datos iniciales:")
print(df0.dtypes)

# Identificar columnas que deberían ser numéricas
columnas_numericas = ["Temperature", "Humidity", "PM 2.5", "PM 10", "PM 1"]

# Convertir cada columna a numérico, forzando errores a NaN
for col in columnas_numericas:
    if col in df0.columns:
        print(f"\nConvirtiendo columna '{col}'...")
        
        # Guardar valores originales para comparar
        valores_originales = df0[col].head(5).tolist()
        
        # Convertir a numérico
        df0[col] = pd.to_numeric(df0[col], errors='coerce')
        
        # Contar valores convertidos y no convertidos
        total_valores = len(df0[col])
        valores_nan = df0[col].isna().sum()
        valores_convertidos = total_valores - valores_nan
        
        print(f"  Valores originales (primeros 5): {valores_originales}")
        print(f"  Valores convertidos: {valores_convertidos}/{total_valores}")
        print(f"  Valores no convertidos (NaN): {valores_nan}")

# Crear DataFrame con índice temporal
df1 = parse_datetime_index(df0, format="%d/%m/%Y %H:%M:%S")

print("\n✅ Tipos de datos después de la conversión:")
print(df1.dtypes)

# ======================================================
# LIMPIEZA ADICIONAL ANTES DEL RESAMPLE (SOLUCIÓN AL ERROR)
# ======================================================

print("\n🧹 Realizando limpieza adicional antes del resample...")

# 1. Eliminar columnas vacías o con nombres vacíos
df1 = df1.loc[:, ~df1.columns.astype(str).str.contains('^Unnamed')]
df1 = df1.loc[:, ~df1.columns.astype(str).str.contains('^$')]

# 2. Seleccionar solo columnas numéricas conocidas
columnas_a_mantener = ['Temperature', 'Humidity', 'PM 1', 'PM 2.5', 'PM 10']
columnas_existentes = [col for col in columnas_a_mantener if col in df1.columns]

print(f"📋 Columnas a mantener: {columnas_existentes}")

# 3. Verificar que todas las columnas sean numéricas
for col in columnas_existentes:
    if df1[col].dtype not in ['int64', 'float64']:
        print(f"⚠️  Columna '{col}' no es numérica, convirtiendo...")
        df1[col] = pd.to_numeric(df1[col], errors='coerce')

# 4. Eliminar filas donde todas las columnas sean NaN
df1 = df1.dropna(how='all')

print(f"\n📊 DataFrame después de limpieza:")
print(f"  - Forma: {df1.shape[0]} filas × {df1.shape[1]} columnas")
print(f"  - Tipos de datos: {df1.dtypes.to_dict()}")

# ======================================================
# RESAMPLE CON SEGURIDAD
# ======================================================

print("\n📊 Realizando resample a 10 minutos...")
try:
    # Opción 1: Usar numeric_only=True para seguridad
    df1 = df1.resample("10min").mean(numeric_only=True)
    print("✅ Resample completado exitosamente con numeric_only=True")
    
except Exception as e:
    print(f"⚠️  Error con numeric_only=True: {e}")
    print("🔄 Intentando método alternativo...")
    
    # Opción 2: Método alternativo manual
    try:
        # Crear lista para almacenar resultados
        resample_data = []
        
        # Para cada columna numérica
        for col in df1.columns:
            if df1[col].dtype in ['int64', 'float64']:
                # Resample por columna
                col_resampled = df1[col].resample("10min").mean()
                resample_data.append(col_resampled)
        
        # Combinar resultados
        df1 = pd.concat(resample_data, axis=1)
        print("✅ Resample completado exitosamente con método alternativo")
        
    except Exception as e2:
        print(f"❌ Error en método alternativo: {e2}")
        print("⚠️  Continuando sin resample...")
        # Mantener df1 sin cambios

print(f"📊 Nueva forma después del resample: {df1.shape[0]} filas × {df1.shape[1]} columnas")

# Mostrar estadísticas
print("\n📈 Estadísticas descriptivas:")
print(df1.describe().transpose())

fig = plot_time_series(df1, variable="Temperature", units="°C", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="Humidity", units="%", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="PM 10", units="µg/m³", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="PM 2.5", units="µg/m³", time_unit="Day")
plt.show()

df2 = df1.copy()

vars_to_impute = ["Temperature", "Humidity", "PM 10", "PM 2.5"]

for var in vars_to_impute:
    # Marcar NaN antes de imputar
    df2[f"{var}_imputed"] = df2[var].isna()

    # Calcular medias por hora:minuto
    means = df2.groupby(df2.index.time)[var].transform("mean")

    # Llenar SOLO los NaN, sin alterar valores originales
    df2[var] = df2[var].fillna(means)

df2 = df2.loc[:, ~df2.columns.str.endswith("_imputed")]
# Ver primeras filas del nuevo DataFrame
print(df2.head())

# Ver solo los datos imputados de cada variable
print(df2[[col for col in df2.columns if "imputed" in col]].sum())
df2 = df2.loc[:, ~df2.columns.str.endswith("_imputed")]

fig = plot_time_series(df2, variable="Temperature", units="°C", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="Humidity", units="%", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="PM 10", units="µg/m³", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="PM 2.5", units="µg/m³", time_unit="Day")
plt.show()

# ======================================================
# MODIFICACIÓN CRÍTICA: SELECCIÓN DE ÚLTIMOS 1200 DATOS Y ELIMINACIÓN DE ÚLTIMOS 2 DÍAS
# ======================================================
print("\n" + "="*60)
print("📊 SELECCIÓN DE DATOS PARA MODELADO")
print("="*60)

# Copiar el DataFrame
df3 = df2.copy()

print(f"📊 Datos totales disponibles: {len(df3)} registros")

# ======================================================
# PASO 1: SELECCIONAR ÚLTIMOS 1200 DATOS
# ======================================================

# Obtener los últimos 1200 datos (aproximadamente 200 horas con datos cada 10 minutos)
# Si hay menos de 1200 datos, usar todos los disponibles
total_datos = len(df3)
datos_a_usar = min(1200, total_datos)

# Seleccionar los últimos N datos
df3_temp = df3.tail(datos_a_usar).copy()

print(f"✅ Últimos {len(df3_temp)} datos seleccionados para procesar")
print(f"📅 Rango inicial: {df3_temp.index[0]} a {df3_temp.index[-1]}")

# ======================================================
# PASO 2: ELIMINAR LOS ÚLTIMOS 2 DÍAS DE ESOS 1200 DATOS
# ======================================================

# Encontrar las fechas únicas en los datos seleccionados
fechas_unicas = sorted(set(df3_temp.index.date))
print(f"\n📅 Fechas únicas en los datos seleccionados: {len(fechas_unicas)} días")

if len(fechas_unicas) > 2:
    # Seleccionar los DOS últimos días
    dias_a_eliminar = fechas_unicas[-2:]  # Los dos últimos días
    
    print(f"🗑️  Eliminando datos de los últimos 2 días:")
    for dia in dias_a_eliminar:
        print(f"   - {dia.strftime('%Y-%m-%d')}")
    
    # Convertir a lista de strings para comparación
    dias_a_eliminar_str = [d.strftime("%Y-%m-%d") for d in dias_a_eliminar]
    
    # Crear una máscara booleana
    mask = df3_temp.index.strftime("%Y-%m-%d").isin(dias_a_eliminar_str)
    
    # Contar cuántos registros se eliminarán
    registros_a_eliminar = mask.sum()
    print(f"   Total de registros a eliminar: {registros_a_eliminar}")
    
    # Eliminar los dos últimos días
    df3 = df3_temp[~mask].copy()
    
    print(f"\n✅ Datos después de eliminar últimos 2 días:")
    print(f"   - Registros restantes: {len(df3)}")
    print(f"   - Rango final: {df3.index[0]} a {df3.index[-1]}")
    
else:
    # Si hay 2 días o menos, usar todos los datos disponibles
    print(f"⚠️  Solo hay {len(fechas_unicas)} días de datos, usando todos disponibles")
    df3 = df3_temp.copy()

# ======================================================
# PASO 3: ELIMINAR COLUMNA PM 1 (si existe)
# ======================================================
df3 = df3.drop(columns=["PM 1"], errors="ignore")

# Verificación final
print(f"\n📋 Resumen final:")
print(f"   - Total registros para modelado: {len(df3)}")
print(f"   - Columnas: {list(df3.columns)}")
print(f"   - Rango temporal: {df3.index[0]} a {df3.index[-1]}")
print(f"   - Días cubiertos: {(df3.index[-1] - df3.index[0]).days} días")

# Mostrar las primeras y últimas filas
print(f"\n🔍 Primeras 3 filas:")
print(df3.head(3))
print(f"\n🔍 Últimas 3 filas:")
print(df3.tail(3))

# ======================================================
# CONFIGURAR CARPETA DE SALIDA SIMPLIFICADA
# ======================================================
print("\n" + "=" * 60)
print("📁 CONFIGURANDO CARPETA DE SALIDA (pronosticos/)")
print("=" * 60)

carpeta_pronosticos = configurar_carpeta_salida()

# ======================================================
# 1. RESAMPLEO A DATOS POR HORA CON FRECUENCIA EXPLÍCITA
# ======================================================
# Asegurar que el índice tenga frecuencia para SARIMA
df_hourly = df3.resample("H").mean().dropna()

# Asignar frecuencia explícita al índice (IMPORTANTE PARA SARIMA)
if not df_hourly.index.freq:
    print("⚠️  Asignando frecuencia horaria al índice...")
    df_hourly = df_hourly.asfreq('H')

variables = ["Temperature", "Humidity", "PM 2.5", "PM 10"]

# ======================================================
# 2. OPTIMIZADOR SARIMA (SIN PMDARIMA)
# ======================================================
p = d = q = [0, 1]
P = D = Q = [0, 1]
m = 12  # estacionalidad de 12 horas


def buscar_mejor_modelo(series):
    mejor_aic = float("inf")
    mejor_modelo = None
    mejor_orden = None
    mejor_orden_season = None
    mejores_parametros = None
    mejor_summary = None

    for pi in p:
        for di in d:
            for qi in q:
                for Pi in P:
                    for Di in D:
                        for Qi in Q:
                            orden = (pi, di, qi)
                            orden_seas = (Pi, Di, Qi, m)

                            try:
                                modelo = SARIMAX(
                                    series,
                                    order=orden,
                                    seasonal_order=orden_seas,
                                    enforce_stationarity=False,
                                    enforce_invertibility=False,
                                ).fit(disp=False, maxiter=200)

                                if modelo.aic < mejor_aic:
                                    mejor_aic = modelo.aic
                                    mejor_modelo = modelo
                                    mejor_orden = orden
                                    mejor_orden_season = orden_seas
                                    mejores_parametros = modelo.params
                                    mejor_summary = modelo.summary()

                            except:
                                continue

    return (
        mejor_modelo,
        mejor_orden,
        mejor_orden_season,
        mejor_aic,
        mejores_parametros,
        mejor_summary,
    )

# ======================================================
# 3. FUNCIÓN PARA OBTENER ECUACIÓN MATEMÁTICA
# ======================================================
def obtener_ecuacion_sarima(modelo, orden, orden_seas):
    """
    Genera la ecuación matemática del modelo SARIMA
    """
    p, d, q = orden
    P, D, Q, m = orden_seas

    # Obtener parámetros
    params = modelo.params

    # Inicializar partes de la ecuación
    parte_ar = ""
    parte_ma = ""
    parte_sar = ""
    parte_sma = ""

    # Coeficientes AR (no estacional)
    for i in range(1, p + 1):
        if f"ar.L{i}" in params:
            coef = params[f"ar.L{i}"]
            parte_ar += f" + {coef:.4f}·y_t-{i}"

    # Coeficientes MA (no estacional)
    for i in range(1, q + 1):
        if f"ma.L{i}" in params:
            coef = params[f"ma.L{i}"]
            parte_ma += f" + {coef:.4f}·ε_t-{i}"

    # Coeficientes SAR (estacional)
    for i in range(1, P + 1):
        if f"ar.S.L{m*i}" in params:
            coef = params[f"ar.S.L{m*i}"]
            parte_sar += f" + {coef:.4f}·y_t-{m*i}"

    # Coeficientes SMA (estacional)
    for i in range(1, Q + 1):
        if f"ma.S.L{m*i}" in params:
            coef = params[f"ma.S.L{m*i}"]
            parte_sma += f" + {coef:.4f}·ε_t-{m*i}"

    # Constante
    constante = ""
    if "intercept" in params:
        constante = f"{params['intercept']:.4f} + "
    elif "const" in params:
        constante = f"{params['const']:.4f} + "

    # Construir ecuación
    if d == 0 and D == 0:
        ecuacion = f"y_t = {constante}"
    else:
        # Para modelos con diferenciación
        ecuacion = "Δ^d Δ_s^D y_t = "
        if constante.strip():
            ecuacion = f"Δ^d Δ_s^D y_t = {constante}"

    # Agregar partes
    if parte_ar:
        ecuacion += parte_ar[3:] if ecuacion.endswith("= ") else parte_ar
    if parte_ma:
        ecuacion += parte_ma
    if parte_sar:
        ecuacion += parte_sar
    if parte_sma:
        ecuacion += parte_sma

    if parte_ar or parte_ma or parte_sar or parte_sma:
        ecuacion += " + ε_t"
    else:
        ecuacion += "ε_t"

    return ecuacion

# ======================================================
# 4. FUNCIÓN PARA MOSTRAR PARÁMETROS COMO EN LA IMAGEN
# ======================================================
def mostrar_parametros_tabla(modelo, orden, orden_seas, aic):
    """
    Muestra los parámetros en formato de tabla como en la imagen
    """
    params = modelo.params
    p, d, q = orden
    P, D, Q, m = orden_seas

    print("\n" + "=" * 60)
    print("PARÁMETROS DEL MODELO SARIMA")
    print("=" * 60)

    # Crear lista de parámetros
    parametros_lista = []

    # Parámetros AR
    for i in range(1, p + 1):
        key = f"ar.L{i}"
        if key in params:
            parametros_lista.append((f"φ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros MA
    for i in range(1, q + 1):
        key = f"ma.L{i}"
        if key in params:
            parametros_lista.append((f"θ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros SAR
    for i in range(1, P + 1):
        key = f"ar.S.L{m*i}"
        if key in params:
            parametros_lista.append((f"Φ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros SMA
    for i in range(1, Q + 1):
        key = f"ma.S.L{m*i}"
        if key in params:
            parametros_lista.append((f"Θ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Constante
    if "intercept" in params:
        parametros_lista.append(
            ("intercept", params["intercept"], modelo.bse.get("intercept", "N/A"))
        )
    elif "const" in params:
        parametros_lista.append(
            ("const", params["const"], modelo.bse.get("const", "N/A"))
        )

    # Varianza del error
    if "sigma2" in params:
        parametros_lista.append(
            ("σ²", params["sigma2"], modelo.bse.get("sigma2", "N/A"))
        )

    # Mostrar tabla
    print(f"\nOrden: SARIMA{orden}{orden_seas}")
    print(f"AIC: {aic:.2f}")
    print("\n" + "-" * 60)
    print(f"{'Parámetro':<15} {'Valor':<15} {'Error estándar':<15}")
    print("-" * 60)

    for nombre, valor, error in parametros_lista:
        if isinstance(error, (int, float)):
            print(f"{nombre:<15} {valor:<15.4f} {error:<15.4f}")
        else:
            print(f"{nombre:<15} {valor:<15.4f} {str(error):<15}")

    print("-" * 60)

# ======================================================
# 5. FUNCIÓN SIMPLIFICADA PARA GUARDAR PRONÓSTICO COMO JSON
# ======================================================
def guardar_pronostico_json(modelo, serie, variable, pasos=72):
    """Guarda el pronóstico completo en un archivo JSON"""
    try:
        if carpeta_pronosticos is None:
            print("⚠️  No se pudo crear carpeta, no se guardará el pronóstico")
            return None
        
        # Obtener pronóstico
        pred = modelo.get_forecast(steps=pasos)
        media = pred.predicted_mean
        conf_80 = pred.conf_int(alpha=0.20)
        conf_95 = pred.conf_int(alpha=0.05)
        
        # Obtener última fecha histórica
        ultima_fecha_historica = serie.index[-1]
        
        # Inferir frecuencia
        freq = pd.infer_freq(serie.index) or 'H'
        
        # Crear fechas para el pronóstico
        if isinstance(freq, str):
            fechas_pronostico = pd.date_range(
                start=ultima_fecha_historica + pd.Timedelta(hours=1), 
                periods=pasos, 
                freq=freq
            )
        else:
            fechas_pronostico = [ultima_fecha_historica + (i+1) * freq for i in range(pasos)]
        
        # Preparar datos del pronóstico
        pronostico_data = []
        for i in range(pasos):
            pronostico_data.append({
                'fecha': fechas_pronostico[i].strftime('%Y-%m-%d %H:%M:%S'),
                'pronostico': float(media.values[i]),
                'limite_inferior_80': float(conf_80.iloc[i, 0]),
                'limite_superior_80': float(conf_80.iloc[i, 1]),
                'limite_inferior_95': float(conf_95.iloc[i, 0]),
                'limite_superior_95': float(conf_95.iloc[i, 1])
            })
        
        # Información del modelo
        orden = modelo.specification.order
        orden_seas = modelo.specification.seasonal_order
        
        # Obtener ecuación
        ecuacion = obtener_ecuacion_sarima(modelo, orden, orden_seas)
        
        # Crear estructura completa del JSON
        datos_completos = {
            'metadata': {
                'variable': variable,
                'modelo': f'SARIMA{orden}{orden_seas}',
                'fecha_entrenamiento': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'fecha_ultimo_dato': ultima_fecha_historica.strftime('%Y-%m-%d %H:%M:%S'),
                'valor_ultimo_dato': float(serie.iloc[-1]),
                'horizonte_pronostico': pasos,
                'unidades': get_units(variable),
                'ecuacion': ecuacion,
                'metricas': {
                    'aic': float(modelo.aic),
                    'bic': float(modelo.bic),
                    'hqic': float(modelo.hqic),
                    'log_likelihood': float(modelo.llf),
                    'num_observaciones': int(modelo.nobs)
                }
            },
            'parametros': {str(k): float(v) for k, v in modelo.params.items()},
            'pronostico': pronostico_data
        }
        
        # Guardar en JSON
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        nombre_archivo = f"pronostico_{variable}.json"
        ruta_completa = os.path.join(carpeta_pronosticos, nombre_archivo)
        
        with open(ruta_completa, 'w', encoding='utf-8') as f:
            json.dump(datos_completos, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Pronóstico JSON guardado en: {ruta_completa}")
        
        return ruta_completa
        
    except Exception as e:
        print(f"⚠️  Error guardando pronóstico JSON para {variable}: {e}")
        import traceback
        traceback.print_exc()
        return None

def get_units(variable):
    """Obtiene las unidades para cada variable"""
    units = {
        "Temperature": "°C",
        "Humidity": "%",
        "PM 2.5": "µg/m³",
        "PM 10": "µg/m³"
    }
    return units.get(variable, "")

# ======================================================
# 6. FUNCIÓN PARA CREAR RESUMEN GENERAL COMO JSON
# ======================================================
def crear_resumen_general_json(resultados, ecuaciones, df_hourly, variables):
    """Crea un resumen general de todos los modelos en un solo JSON"""
    try:
        if carpeta_pronosticos is None:
            return None
            
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        
        # Crear estructura del resumen
        resumen_general = {
            'metadata': {
                'fecha_generacion': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
                'fecha_ultimo_dato': df_hourly.index[-1].strftime('%Y-%m-%d %H:%M:%S'),
                'num_variables': len(variables),
                'total_observaciones': len(df_hourly),
                'rango_datos': {
                    'inicio': df_hourly.index[0].strftime('%Y-%m-%d %H:%M:%S'),
                    'fin': df_hourly.index[-1].strftime('%Y-%m-%d %H:%M:%S')
                }
            },
            'modelos': {}
        }
        
        for var in variables:
            if var in resultados:
                modelo = resultados[var]
                orden = modelo.specification.order
                orden_seas = modelo.specification.seasonal_order
                
                resumen_general['modelos'][var] = {
                    'orden': str(orden),
                    'orden_estacional': str(orden_seas),
                    'ecuacion': ecuaciones.get(var, 'No disponible'),
                    'metricas': {
                        'aic': float(modelo.aic),
                        'bic': float(modelo.bic),
                        'hqic': float(modelo.hqic),
                        'log_likelihood': float(modelo.llf),
                        'num_observaciones': int(modelo.nobs)
                    },
                    'ultimo_valor': float(df_hourly[var].iloc[-1]),
                    'unidades': get_units(var)
                }
        
        # Guardar resumen
        nombre_archivo = "resumen_modelos.json"
        ruta_completa = os.path.join(carpeta_pronosticos, nombre_archivo)
        
        with open(ruta_completa, 'w', encoding='utf-8') as f:
            json.dump(resumen_general, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Resumen general JSON guardado en: {ruta_completa}")
        
        return ruta_completa
        
    except Exception as e:
        print(f"⚠️  Error creando resumen general JSON: {e}")
        return None

# ======================================================
# 7. EJECUCIÓN COMPLETA POR VARIABLE CON MANEJO DE ERRORES
# ======================================================
limites = {
    "Temperature": None,
    "Humidity": None,
    "PM 2.5": 37,  # valor OMS o Colombia
    "PM 10": 75,
}

resultados = {}
ecuaciones = {}
archivos_guardados = []

print(f"\n{'='*80}")
print("🚀 INICIANDO PROCESO DE MODELADO SARIMA")
print(f"{'='*80}")

for var in variables:
    print(f"\n{'='*80}")
    print(f" OPTIMIZANDO: {var}")
    print(f"{'='*80}")

    serie = df_hourly[var]

    try:
        modelo, orden, orden_s, aic, parametros, summary = buscar_mejor_modelo(serie)

        print(f"\nMejor modelo para {var}: SARIMA{orden}{orden_s}")
        print(f"AIC = {aic:.2f}")

        # Obtener y mostrar ecuación matemática
        try:
            ecuacion = obtener_ecuacion_sarima(modelo, orden, orden_s)
            print(f"\nEcuación matemática:")
            print(f"{ecuacion}")
        except Exception as e:
            print(f"⚠️  Error obteniendo ecuación: {e}")
            ecuacion = "No disponible"

        # Mostrar parámetros en formato de tabla
        try:
            mostrar_parametros_tabla(modelo, orden, orden_s, aic)
        except Exception as e:
            print(f"⚠️  Error mostrando parámetros: {e}")

        # Guardar resultados en diccionarios
        resultados[var] = modelo
        ecuaciones[var] = ecuacion
        
        # Guardar pronóstico como JSON
        try:
            ruta_json = guardar_pronostico_json(modelo, serie, var, pasos=72)
            if ruta_json:
                archivos_guardados.append(("JSON", var, ruta_json))
        except Exception as e:
            print(f"⚠️  Error guardando JSON para {var}: {e}")
            
    except Exception as e:
        print(f"❌ Error procesando {var}: {e}")
        print(f"⚠️  Saltando variable {var}...")

# ======================================================
# 8. CREAR RESUMEN GENERAL COMO JSON
# ======================================================
try:
    ruta_resumen = crear_resumen_general_json(resultados, ecuaciones, df_hourly, variables)
    if ruta_resumen:
        archivos_guardados.append(("Resumen JSON", "General", ruta_resumen))
except Exception as e:
    print(f"⚠️  Error creando resumen general JSON: {e}")

# ======================================================
# 9. RESUMEN FINAL DE TODOS LOS MODELOS
# ======================================================
print(f"\n{'='*80}")
print(" 📊 RESUMEN FINAL DE MODELOS SARIMA")
print(f"{'='*80}")

for var in variables:
    if var in resultados:
        print(f"\n{var}:")
        print(f"  Modelo: SARIMA{resultados[var].specification.order}")
        print(f"          {resultados[var].specification.seasonal_order}")
        print(f"  AIC: {resultados[var].aic:.2f}")
        print(f"  Ecuación: {ecuaciones.get(var, 'No disponible')}")
        print(f"  Número de observaciones: {len(df_hourly[var])}")
        print(f"  Último dato: {df_hourly[var].iloc[-1]:.2f} ({df_hourly.index[-1].strftime('%Y-%m-%d %H:%M')})")
    else:
        print(f"\n{var}: No se pudo ajustar modelo")

# ======================================================
# 10. RESUMEN DE ARCHIVOS GUARDADOS
# ======================================================
print(f"\n{'='*80}")
print(" 💾 ARCHIVOS GUARDADOS EN pronosticos/")
print(f"{'='*80}")

if archivos_guardados:
    for tipo, variable, ruta in archivos_guardados:
        print(f"  {tipo} - {variable}: {os.path.basename(ruta)}")
    
    print(f"\n📊 Total de archivos JSON generados: {len(archivos_guardados)}")
    
    # Mostrar contenido real de la carpeta
    if carpeta_pronosticos and os.path.exists(carpeta_pronosticos):
        archivos_en_carpeta = os.listdir(carpeta_pronosticos)
        print(f"\n📂 Contenido actual de {carpeta_pronosticos}:")
        for archivo in archivos_en_carpeta:
            if archivo.endswith('.json'):
                ruta_completa = os.path.join(carpeta_pronosticos, archivo)
                tamaño = os.path.getsize(ruta_completa)
                tamaño_kb = tamaño / 1024
                print(f"  📄 {archivo} ({tamaño_kb:.1f} KB)")
else:
    print("  No se guardaron archivos.")

print(f"\n{'='*80}")
print(" ✅ PROCESO COMPLETADO EXITOSAMENTE")
print(f"{'='*80}")

# Mostrar ubicación de la carpeta
if carpeta_pronosticos:
    print(f"\n📁 Carpeta de pronósticos: {carpeta_pronosticos}")
    
    # Verificar contenido
    if os.path.exists(carpeta_pronosticos):
        archivos = os.listdir(carpeta_pronosticos)
        if archivos:
            print(f"📋 Archivos JSON en la carpeta ({len(archivos)} total):")
            json_files = [f for f in archivos if f.endswith('.json')]
            for archivo in json_files:
                tamaño = os.path.getsize(os.path.join(carpeta_pronosticos, archivo))
                tamaño_kb = tamaño / 1024
                print(f"  ✅ {archivo} ({tamaño_kb:.1f} KB)")
        else:
            print("  📭 La carpeta está vacía")
else:
    print("⚠️  No se pudo crear la carpeta 'pronosticos'")

# ======================================================
# 11. RESUMEN DE ACTUALIZACIÓN DE DATOS
# ======================================================
print(f"\n{'='*80}")
print(" 🔄 RESUMEN DE ACTUALIZACIÓN DE DATOS")
print(f"{'='*80}")

if 'df0' in locals() and not df0.empty:
    print(f"📊 Datos cargados de Google Sheets:")
    print(f"  - Total registros: {len(df0)}")
    print(f"  - Primera fecha: {df0['date'].iloc[0]}")
    print(f"  - Última fecha: {df0['date'].iloc[-1]}")
    
    try:
        ultima_fecha_str = df0['date'].iloc[-1]
        ultima_fecha = pd.to_datetime(ultima_fecha_str, format="%d/%m/%Y %H:%M:%S")
        hoy = datetime.now()
        
        print(f"\n📅 Análisis de actualización:")
        print(f"  - Último registro: {ultima_fecha.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  - Fecha actual: {hoy.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"  - Diferencia: {(hoy - ultima_fecha).days} días")
        
        if (hoy - ultima_fecha).days <= 2:
            print("  ✅ Datos actualizados (menos de 2 días de diferencia)")
        else:
            print(f"  ⚠️  Los datos tienen más de {(hoy - ultima_fecha).days} días")
            
    except Exception as e:
        print(f"  ⚠️  Error analizando fechas: {e}")

# ======================================================
# 12. LIMPIAR ARCHIVOS TEMPORALES GRANDES
# ======================================================
print(f"\n{'='*80}")
print(" 🧹 LIMPIANDO ARCHIVOS TEMPORALES")
print("=" * 80)

# Listar archivos temporales grandes y eliminarlos si existen
archivos_a_eliminar = []
for root, dirs, files in os.walk('.'):
    for file in files:
        if file.endswith('.pkl'):
            ruta_completa = os.path.join(root, file)
            archivos_a_eliminar.append(ruta_completa)

if archivos_a_eliminar:
    print(f"⚠️  Encontrados {len(archivos_a_eliminar)} archivos .pkl grandes:")
    for archivo in archivos_a_eliminar:
        try:
            tamaño = os.path.getsize(archivo)
            tamaño_mb = tamaño / (1024 * 1024)
            print(f"  - {archivo} ({tamaño_mb:.2f} MB)")
            
            # Eliminar automáticamente
            os.remove(archivo)
            print(f"    ✅ Eliminado")
        except:
            pass
    print("✅ Archivos temporales grandes eliminados")
else:
    print("✅ No se encontraron archivos .pkl grandes")

print(f"\n{'='*80}")
print(" 🎯 CONFIGURACIÓN SIMPLIFICADA COMPLETADA")
print("    • Solo archivos JSON en carpeta pronosticos/")
print("    • Últimos 1200 datos procesados")
print("    • Últimos 2 días eliminados")
print(f"{'='*80}")
