# -*- coding: utf-8 -*-
"""Modelo_Sarima.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iAFMXztN6AvkjVaC3_b2wtbi-jGTxS8R
"""

import os
import pickle
import json
import warnings
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from datetime import datetime, timedelta

warnings.filterwarnings("ignore")

# ======================================================
# URL DE GOOGLE SHEETS (definida a nivel global)
# ======================================================
SHEET_URL = "https://docs.google.com/spreadsheets/d/1x1FeUolFWlR07tgrc6F4cgeUhJYV7uQ5yuRTBHO8jWI/edit?gid=0#gid=0"

# ======================================================
# CONFIGURACIÓN DE CARPETAS DE SALIDA
# ======================================================
def configurar_carpetas_salida():
    """Configura las carpetas donde se guardarán los resultados"""
    try:
        # En Colab, guardar en Drive
        if 'IN_COLAB' in globals() and IN_COLAB:
            carpeta_base = "/content/drive/MyDrive/pronosticos"
        else:
            # En GitHub Actions o local
            carpeta_base = "./pronosticos"
        
        # Crear subcarpetas (solo las necesarias)
        carpetas = {
            'base': carpeta_base,
            'graficos': os.path.join(carpeta_base, 'graficos'),
            'datos': os.path.join(carpeta_base, 'datos'),
            'resumen': os.path.join(carpeta_base, 'resumen')
            # NOTA: Omitimos la carpeta 'modelos' para evitar archivos grandes
        }
        
        for carpeta in carpetas.values():
            os.makedirs(carpeta, exist_ok=True)
            print(f"✅ Carpeta creada/verificada: {carpeta}")
        
        return carpetas
    except Exception as e:
        print(f"⚠️  Error configurando carpetas: {e}")
        return None

# ======================================================
# 1. FUNCIÓN DE CONEXIÓN A GOOGLE SHEETS (COLAB + GITHUB)
# ======================================================


def conectar_a_google_sheets():
    """
    Conecta a Google Sheets de manera inteligente
    - En Colab: usa autenticación normal
    - En GitHub: puede usar Service Account
    """

    try:
        # Verificar si estamos en Google Colab
        try:
            from google.colab import auth

            IN_COLAB = True
        except:
            IN_COLAB = False

        if IN_COLAB:
            # ========== MODO COLAB ==========
            print("🔑 Autenticando en Google Colab...")

            # Autenticación interactiva
            auth.authenticate_user()
            from google.auth import default

            creds, _ = default()

            import gspread

            gc = gspread.authorize(creds)

        else:
            # ========== MODO GITHUB/LOCAL ==========
            import gspread

            # Intentar con variable de entorno (para GitHub Actions)
            creds_json = os.getenv("GOOGLE_SHEETS_CREDS")

            if creds_json:
                print("🔑 Usando Service Account desde variable de entorno...")
                from google.oauth2.service_account import Credentials

                creds_dict = json.loads(creds_json)
                scope = ["https://www.googleapis.com/auth/spreadsheets"]
                credentials = Credentials.from_service_account_info(
                    creds_dict, scopes=scope
                )
                gc = gspread.authorize(credentials)
            else:
                # Intentar autenticación normal (fallback)
                print("⚠️  Intentando autenticación normal...")
                gc = gspread.oauth()  # Esto abrirá navegador en local

        # Abrir la hoja
        spreadsheet = gc.open_by_url(SHEET_URL)
        worksheet = spreadsheet.get_worksheet(0)

        print("✅ Conexión exitosa a Google Sheets")
        return worksheet

    except Exception as e:
        print(f"❌ Error conectando a Google Sheets: {e}")
        print("⚠️  Usando datos de ejemplo para continuar...")
        return None


# ======================================================
# 2. CONFIGURACIÓN INICIAL DE COLAB
# ======================================================

# Montar Google Drive (solo funciona en Colab)
try:
    from google.colab import drive

    drive.mount("/content/drive", force_remount=False)
    IN_COLAB = True
    print("✅ Google Drive montado")

except:
    IN_COLAB = False
    print("⚠️  No es Google Colab, omitiendo montaje de Drive")

# ======================================================
# 3. INSTALAR DEPENDENCIAS (SOLO COLAB)
# ======================================================

if IN_COLAB:
    print("📦 Instalando dependencias en Colab...")
else:
    print("✅ En GitHub, las dependencias se instalan desde requirements.txt")

# ======================================================
# 4. IMPORTAR BIBLIOTECAS RESTANTES
# ======================================================

import gspread
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from statsmodels.tsa.statespace.sarimax import SARIMAX
import matplotlib.dates as mdates

# Cargar jupyter-black (solo Colab)
if IN_COLAB:
    import jupyter_black

    jupyter_black.load()

# ======================================================
# 5. REEMPLAZAR LA IMPORTACIÓN DE 'direl_ts_tool_kit'
# ======================================================


def parse_datetime_index(df, date_column="date", format="%d/%m/%Y %H:%M:%S"):
    """
    Convierte una columna de fecha a datetime y la usa como índice
    (Reemplaza a la función de direl_ts_tool_kit)
    """
    df_copy = df.copy()
    df_copy[date_column] = pd.to_datetime(
        df_copy[date_column], format=format, errors="coerce"
    )
    df_copy.set_index(date_column, inplace=True)
    return df_copy


def plot_time_series(df, variable, units="", time_unit="Day"):
    """
    Grafica una serie de tiempo
    (Versión simplificada de la función original)
    """
    fig, ax = plt.subplots(figsize=(12, 5))

    ax.plot(df.index, df[variable], linewidth=1)
    ax.set_title(f"Serie de Tiempo - {variable}")
    ax.set_xlabel(f"Tiempo ({time_unit})")
    ax.set_ylabel(f"{variable} {units}")
    ax.grid(True, alpha=0.3)

    # Formato de fechas
    ax.xaxis.set_major_formatter(mdates.DateFormatter("%d/%m %H:%M"))
    plt.setp(ax.xaxis.get_majorticklabels(), rotation=45)

    plt.tight_layout()
    return fig


# ======================================================
# 6. CONECTAR Y CARGAR DATOS
# ======================================================

print("\n" + "=" * 60)
print("📥 CARGANDO DATOS DESDE GOOGLE SHEETS")
print("=" * 60)

# Conectar a Google Sheets
worksheet = conectar_a_google_sheets()

if worksheet is not None:
    # Obtener todos los datos
    datos = worksheet.get_all_values()

    # Convertir a DataFrame
    df0 = pd.DataFrame(datos[1:], columns=datos[0])

    print(f"✅ Datos cargados desde Google Sheets")
    print(f"📊 Dimensiones: {df0.shape[0]} filas × {df0.shape[1]} columnas")
    print(f"🔗 URL: {SHEET_URL}")

else:
    # ========== DATOS DE EJEMPLO (si falla la conexión) ==========
    print("📝 Usando datos de ejemplo para demostración...")

    # Crear datos de ejemplo simples
    import numpy as np

    fechas = pd.date_range(start="2024-01-01", periods=100, freq="H")

    datos_ejemplo = {
        "Date": [f.strftime("%d/%m/%Y %H:%M:%S") for f in fechas],
        "Temperature": 25 + 5 * np.sin(np.linspace(0, 10, 100)),
        "Humidity": 60 + 10 * np.cos(np.linspace(0, 8, 100)),
        "PM 2.5(µg/m³)": 20 + 8 * np.random.randn(100),
        "PM 10 (µg/m³)": 40 + 12 * np.random.randn(100),
        "PM 1.0 (µg/m³)": 10 + 4 * np.random.randn(100),
    }

    df0 = pd.DataFrame(datos_ejemplo)
    print(f"📊 Datos de ejemplo creados: {df0.shape[0]} filas")

print("\n📋 Primeras filas de datos:")
print(df0.head(2))

df0.rename(
    columns={
        "Date": "date",
        "PM 1.0 (µg/m³)": "PM 1",
        "PM 2.5(µg/m³)": "PM 2.5",
        "PM 10 (µg/m³)": "PM 10",
    },
    inplace=True,
)

# ======================================================
# CONVERSIÓN DE DATOS Y LIMPIEZA
# ======================================================

print("🔍 Verificando tipos de datos iniciales:")
print(df0.dtypes)

# Identificar columnas que deberían ser numéricas
columnas_numericas = ["Temperature", "Humidity", "PM 2.5", "PM 10", "PM 1"]

# Convertir cada columna a numérico, forzando errores a NaN
for col in columnas_numericas:
    if col in df0.columns:
        print(f"\nConvirtiendo columna '{col}'...")
        
        # Guardar valores originales para comparar
        valores_originales = df0[col].head(5).tolist()
        
        # Convertir a numérico
        df0[col] = pd.to_numeric(df0[col], errors='coerce')
        
        # Contar valores convertidos y no convertidos
        total_valores = len(df0[col])
        valores_nan = df0[col].isna().sum()
        valores_convertidos = total_valores - valores_nan
        
        print(f"  Valores originales (primeros 5): {valores_originales}")
        print(f"  Valores convertidos: {valores_convertidos}/{total_valores}")
        print(f"  Valores no convertidos (NaN): {valores_nan}")

# Crear DataFrame con índice temporal
df1 = parse_datetime_index(df0, format="%d/%m/%Y %H:%M:%S")

print("\n✅ Tipos de datos después de la conversión:")
print(df1.dtypes)

# ======================================================
# LIMPIEZA ADICIONAL ANTES DEL RESAMPLE (SOLUCIÓN AL ERROR)
# ======================================================

print("\n🧹 Realizando limpieza adicional antes del resample...")

# 1. Eliminar columnas vacías o con nombres vacíos
df1 = df1.loc[:, ~df1.columns.astype(str).str.contains('^Unnamed')]
df1 = df1.loc[:, ~df1.columns.astype(str).str.contains('^$')]

# 2. Seleccionar solo columnas numéricas conocidas
columnas_a_mantener = ['Temperature', 'Humidity', 'PM 1', 'PM 2.5', 'PM 10']
columnas_existentes = [col for col in columnas_a_mantener if col in df1.columns]

print(f"📋 Columnas a mantener: {columnas_existentes}")

# 3. Verificar que todas las columnas sean numéricas
for col in columnas_existentes:
    if df1[col].dtype not in ['int64', 'float64']:
        print(f"⚠️  Columna '{col}' no es numérica, convirtiendo...")
        df1[col] = pd.to_numeric(df1[col], errors='coerce')

# 4. Eliminar filas donde todas las columnas sean NaN
df1 = df1.dropna(how='all')

print(f"\n📊 DataFrame después de limpieza:")
print(f"  - Forma: {df1.shape[0]} filas × {df1.shape[1]} columnas")
print(f"  - Tipos de datos: {df1.dtypes.to_dict()}")

# ======================================================
# RESAMPLE CON SEGURIDAD
# ======================================================

print("\n📊 Realizando resample a 10 minutos...")
try:
    # Opción 1: Usar numeric_only=True para seguridad
    df1 = df1.resample("10min").mean(numeric_only=True)
    print("✅ Resample completado exitosamente con numeric_only=True")
    
except Exception as e:
    print(f"⚠️  Error con numeric_only=True: {e}")
    print("🔄 Intentando método alternativo...")
    
    # Opción 2: Método alternativo manual
    try:
        # Crear lista para almacenar resultados
        resample_data = []
        
        # Para cada columna numérica
        for col in df1.columns:
            if df1[col].dtype in ['int64', 'float64']:
                # Resample por columna
                col_resampled = df1[col].resample("10min").mean()
                resample_data.append(col_resampled)
        
        # Combinar resultados
        df1 = pd.concat(resample_data, axis=1)
        print("✅ Resample completado exitosamente con método alternativo")
        
    except Exception as e2:
        print(f"❌ Error en método alternativo: {e2}")
        print("⚠️  Continuando sin resample...")
        # Mantener df1 sin cambios

print(f"📊 Nueva forma después del resample: {df1.shape[0]} filas × {df1.shape[1]} columnas")

# Mostrar estadísticas
print("\n📈 Estadísticas descriptivas:")
print(df1.describe().transpose())

fig = plot_time_series(df1, variable="Temperature", units="°C", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="Humidity", units="%", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="PM 10", units="µg/m³", time_unit="Day")
plt.show()

fig = plot_time_series(df1, variable="PM 2.5", units="µg/m³", time_unit="Day")
plt.show()

df2 = df1.copy()

vars_to_impute = ["Temperature", "Humidity", "PM 10", "PM 2.5"]

for var in vars_to_impute:
    # Marcar NaN antes de imputar
    df2[f"{var}_imputed"] = df2[var].isna()

    # Calcular medias por hora:minuto
    means = df2.groupby(df2.index.time)[var].transform("mean")

    # Llenar SOLO los NaN, sin alterar valores originales
    df2[var] = df2[var].fillna(means)

df2 = df2.loc[:, ~df2.columns.str.endswith("_imputed")]
# Ver primeras filas del nuevo DataFrame
print(df2.head())

# Ver solo los datos imputados de cada variable
print(df2[[col for col in df2.columns if "imputed" in col]].sum())
df2 = df2.loc[:, ~df2.columns.str.endswith("_imputed")]

fig = plot_time_series(df2, variable="Temperature", units="°C", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="Humidity", units="%", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="PM 10", units="µg/m³", time_unit="Day")
plt.show()

fig = plot_time_series(df2, variable="PM 2.5", units="µg/m³", time_unit="Day")
plt.show()

# Copiar el DataFrame
df3 = df2.copy()

# Encontrar las fechas únicas y seleccionar los dos últimos días
fechas_unicas = sorted(set(df3.index.date))
dias_a_eliminar = fechas_unicas[-2:]  # Los dos últimos días

# Convertir a lista de strings para comparación
dias_a_eliminar_str = [d.strftime("%Y-%m-%d") for d in dias_a_eliminar]

# Crear una máscara booleana
mask = df3.index.strftime("%Y-%m-%d").isin(dias_a_eliminar_str)

# Eliminar los dos últimos días
df3 = df3[~mask]

# Eliminar columna PM 1
df3 = df3.drop(columns=["PM 1"], errors="ignore")

# Verificar
print(df3.head())
print(df3.tail())

# ======================================================
# CONFIGURAR CARPETAS DE SALIDA
# ======================================================
print("\n" + "=" * 60)
print("📁 CONFIGURANDO CARPETAS DE SALIDA")
print("=" * 60)

carpetas = configurar_carpetas_salida()

# ======================================================
# 1. RESAMPLEO A DATOS POR HORA CON FRECUENCIA EXPLÍCITA
# ======================================================
# Asegurar que el índice tenga frecuencia para SARIMA
df_hourly = df3.resample("H").mean().dropna()

# Asignar frecuencia explícita al índice (IMPORTANTE PARA SARIMA)
if not df_hourly.index.freq:
    print("⚠️  Asignando frecuencia horaria al índice...")
    df_hourly = df_hourly.asfreq('H')

variables = ["Temperature", "Humidity", "PM 2.5", "PM 10"]

# ======================================================
# 2. OPTIMIZADOR SARIMA (SIN PMDARIMA)
# ======================================================
p = d = q = [0, 1]
P = D = Q = [0, 1]
m = 12  # estacionalidad de 12 horas


def buscar_mejor_modelo(series):
    mejor_aic = float("inf")
    mejor_modelo = None
    mejor_orden = None
    mejor_orden_season = None
    mejores_parametros = None
    mejor_summary = None

    for pi in p:
        for di in d:
            for qi in q:
                for Pi in P:
                    for Di in D:
                        for Qi in Q:
                            orden = (pi, di, qi)
                            orden_seas = (Pi, Di, Qi, m)

                            try:
                                modelo = SARIMAX(
                                    series,
                                    order=orden,
                                    seasonal_order=orden_seas,
                                    enforce_stationarity=False,
                                    enforce_invertibility=False,
                                ).fit(disp=False, maxiter=200)

                                if modelo.aic < mejor_aic:
                                    mejor_aic = modelo.aic
                                    mejor_modelo = modelo
                                    mejor_orden = orden
                                    mejor_orden_season = orden_seas
                                    mejores_parametros = modelo.params
                                    mejor_summary = modelo.summary()

                            except:
                                continue

    return (
        mejor_modelo,
        mejor_orden,
        mejor_orden_season,
        mejor_aic,
        mejores_parametros,
        mejor_summary,
    )

# ======================================================
# 3. FUNCIÓN PARA OBTENER ECUACIÓN MATEMÁTICA
# ======================================================
def obtener_ecuacion_sarima(modelo, orden, orden_seas):
    """
    Genera la ecuación matemática del modelo SARIMA
    """
    p, d, q = orden
    P, D, Q, m = orden_seas

    # Obtener parámetros
    params = modelo.params

    # Inicializar partes de la ecuación
    parte_ar = ""
    parte_ma = ""
    parte_sar = ""
    parte_sma = ""

    # Coeficientes AR (no estacional)
    for i in range(1, p + 1):
        if f"ar.L{i}" in params:
            coef = params[f"ar.L{i}"]
            parte_ar += f" + {coef:.4f}·y_t-{i}"

    # Coeficientes MA (no estacional)
    for i in range(1, q + 1):
        if f"ma.L{i}" in params:
            coef = params[f"ma.L{i}"]
            parte_ma += f" + {coef:.4f}·ε_t-{i}"

    # Coeficientes SAR (estacional)
    for i in range(1, P + 1):
        if f"ar.S.L{m*i}" in params:
            coef = params[f"ar.S.L{m*i}"]
            parte_sar += f" + {coef:.4f}·y_t-{m*i}"

    # Coeficientes SMA (estacional)
    for i in range(1, Q + 1):
        if f"ma.S.L{m*i}" in params:
            coef = params[f"ma.S.L{m*i}"]
            parte_sma += f" + {coef:.4f}·ε_t-{m*i}"

    # Constante
    constante = ""
    if "intercept" in params:
        constante = f"{params['intercept']:.4f} + "
    elif "const" in params:
        constante = f"{params['const']:.4f} + "

    # Construir ecuación
    if d == 0 and D == 0:
        ecuacion = f"y_t = {constante}"
    else:
        # Para modelos con diferenciación
        ecuacion = "Δ^d Δ_s^D y_t = "
        if constante.strip():
            ecuacion = f"Δ^d Δ_s^D y_t = {constante}"

    # Agregar partes
    if parte_ar:
        ecuacion += parte_ar[3:] if ecuacion.endswith("= ") else parte_ar
    if parte_ma:
        ecuacion += parte_ma
    if parte_sar:
        ecuacion += parte_sar
    if parte_sma:
        ecuacion += parte_sma

    if parte_ar or parte_ma or parte_sar or parte_sma:
        ecuacion += " + ε_t"
    else:
        ecuacion += "ε_t"

    return ecuacion

# ======================================================
# 4. FUNCIÓN PARA MOSTRAR PARÁMETROS COMO EN LA IMAGEN
# ======================================================
def mostrar_parametros_tabla(modelo, orden, orden_seas, aic):
    """
    Muestra los parámetros en formato de tabla como en la imagen
    """
    params = modelo.params
    p, d, q = orden
    P, D, Q, m = orden_seas

    print("\n" + "=" * 60)
    print("PARÁMETROS DEL MODELO SARIMA")
    print("=" * 60)

    # Crear lista de parámetros
    parametros_lista = []

    # Parámetros AR
    for i in range(1, p + 1):
        key = f"ar.L{i}"
        if key in params:
            parametros_lista.append((f"φ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros MA
    for i in range(1, q + 1):
        key = f"ma.L{i}"
        if key in params:
            parametros_lista.append((f"θ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros SAR
    for i in range(1, P + 1):
        key = f"ar.S.L{m*i}"
        if key in params:
            parametros_lista.append((f"Φ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Parámetros SMA
    for i in range(1, Q + 1):
        key = f"ma.S.L{m*i}"
        if key in params:
            parametros_lista.append((f"Θ_{i}", params[key], modelo.bse.get(key, "N/A")))

    # Constante
    if "intercept" in params:
        parametros_lista.append(
            ("intercept", params["intercept"], modelo.bse.get("intercept", "N/A"))
        )
    elif "const" in params:
        parametros_lista.append(
            ("const", params["const"], modelo.bse.get("const", "N/A"))
        )

    # Varianza del error
    if "sigma2" in params:
        parametros_lista.append(
            ("σ²", params["sigma2"], modelo.bse.get("sigma2", "N/A"))
        )

    # Mostrar tabla
    print(f"\nOrden: SARIMA{orden}{orden_seas}")
    print(f"AIC: {aic:.2f}")
    print("\n" + "-" * 60)
    print(f"{'Parámetro':<15} {'Valor':<15} {'Error estándar':<15}")
    print("-" * 60)

    for nombre, valor, error in parametros_lista:
        if isinstance(error, (int, float)):
            print(f"{nombre:<15} {valor:<15.4f} {error:<15.4f}")
        else:
            print(f"{nombre:<15} {valor:<15.4f} {str(error):<15}")

    print("-" * 60)

# ======================================================
# 5. FUNCIONES PARA GUARDAR RESULTADOS (SOLO FORMATOS PEQUEÑOS)
# ======================================================
def guardar_pronostico_csv(modelo, serie, variable, pasos=72):
    """Guarda el pronóstico en un archivo CSV"""
    try:
        if carpetas is None:
            print("⚠️  No se pudieron crear carpetas, no se guardará el pronóstico")
            return None
            
        pred = modelo.get_forecast(steps=pasos)
        media = pred.predicted_mean
        conf_95 = pred.conf_int(alpha=0.05)
        
        # Crear DataFrame con el pronóstico
        df_pronostico = pd.DataFrame({
            'fecha': media.index,
            'pronostico': media.values,
            'limite_inferior_95': conf_95.iloc[:, 0],
            'limite_superior_95': conf_95.iloc[:, 1]
        })
        
        # Formatear fechas
        df_pronostico['fecha'] = pd.to_datetime(df_pronostico['fecha'])
        df_pronostico['fecha_str'] = df_pronostico['fecha'].dt.strftime('%Y-%m-%d %H:%M:%S')
        
        # Agregar información adicional
        df_pronostico['variable'] = variable
        df_pronostico['fecha_generacion'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
        df_pronostico['horizonte_pronostico'] = f'{pasos} horas'
        
        # Reordenar columnas
        df_pronostico = df_pronostico[[
            'variable', 'fecha', 'fecha_str', 'pronostico',
            'limite_inferior_95', 'limite_superior_95',
            'fecha_generacion', 'horizonte_pronostico'
        ]]
        
        # Guardar en CSV
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        nombre_archivo = f"pronostico_{variable}_{fecha_actual}.csv"
        ruta_completa = os.path.join(carpetas['datos'], nombre_archivo)
        
        df_pronostico.to_csv(ruta_completa, index=False, encoding='utf-8')
        print(f"✅ Pronóstico CSV guardado en: {ruta_completa}")
        
        return ruta_completa
        
    except Exception as e:
        print(f"⚠️  Error guardando pronóstico CSV para {variable}: {e}")
        return None

def guardar_grafico_pronostico(fig, variable):
    """Guarda el gráfico del pronóstico"""
    try:
        if carpetas is None:
            return None
            
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        nombre_archivo = f"pronostico_{variable}_{fecha_actual}.png"
        ruta_completa = os.path.join(carpetas['graficos'], nombre_archivo)
        
        fig.savefig(ruta_completa, dpi=150, bbox_inches='tight')
        print(f"✅ Gráfico PNG guardado en: {ruta_completa}")
        
        return ruta_completa
        
    except Exception as e:
        print(f"⚠️  Error guardando gráfico para {variable}: {e}")
        return None

def guardar_parametros_json(modelo, variable, orden, orden_seas, aic, ecuacion):
    """Guarda solo los parámetros del modelo en formato JSON (archivo pequeño)"""
    try:
        if carpetas is None:
            return None
            
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        nombre_archivo = f"parametros_{variable}_{fecha_actual}.json"
        ruta_completa = os.path.join(carpetas['resumen'], nombre_archivo)
        
        # Extraer solo la información esencial (sin el modelo completo)
        info_modelo = {
            'variable': variable,
            'orden': str(orden),
            'orden_estacional': str(orden_seas),
            'aic': float(aic),
            'ecuacion': ecuacion,
            'fecha_entrenamiento': datetime.now().strftime('%Y-%m-%d %H:%M:%S'),
            'parametros': {str(k): float(v) for k, v in modelo.params.items()},
            'num_observaciones': modelo.nobs,
            'log_likelihood': float(modelo.llf),
            'bic': float(modelo.bic),
            'hqic': float(modelo.hqic)
        }
        
        with open(ruta_completa, 'w', encoding='utf-8') as f:
            json.dump(info_modelo, f, indent=2, ensure_ascii=False)
        
        print(f"✅ Parámetros JSON guardados en: {ruta_completa}")
        
        return ruta_completa
        
    except Exception as e:
        print(f"⚠️  Error guardando parámetros JSON para {variable}: {e}")
        return None

def crear_resumen_general(resultados, ecuaciones, df_hourly, variables):
    """Crea un resumen general de todos los modelos"""
    try:
        if carpetas is None:
            return None
            
        fecha_actual = datetime.now().strftime('%Y%m%d_%H%M')
        
        # Crear resumen en formato CSV
        resumen_data = []
        
        for var in variables:
            if var in resultados:
                modelo = resultados[var]
                resumen_data.append({
                    'variable': var,
                    'orden': str(modelo.specification.order),
                    'orden_estacional': str(modelo.specification.seasonal_order),
                    'aic': float(modelo.aic),
                    'bic': float(modelo.bic),
                    'hqic': float(modelo.hqic),
                    'log_likelihood': float(modelo.llf),
                    'num_observaciones': int(modelo.nobs),
                    'ecuacion': ecuaciones.get(var, 'No disponible'),
                    'fecha_ultimo_dato': df_hourly.index[-1].strftime('%Y-%m-%d %H:%M:%S'),
                    'valor_ultimo_dato': float(df_hourly[var].iloc[-1]),
                    'fecha_generacion': datetime.now().strftime('%Y-%m-%d %H:%M:%S')
                })
        
        df_resumen = pd.DataFrame(resumen_data)
        
        # Guardar en CSV
        ruta_csv = os.path.join(carpetas['resumen'], f"resumen_modelos_{fecha_actual}.csv")
        df_resumen.to_csv(ruta_csv, index=False, encoding='utf-8')
        
        # Guardar en JSON también
        ruta_json = os.path.join(carpetas['resumen'], f"resumen_modelos_{fecha_actual}.json")
        df_resumen.to_json(ruta_json, orient='records', indent=2)
        
        print(f"✅ Resumen CSV guardado en: {ruta_csv}")
        print(f"✅ Resumen JSON guardado en: {ruta_json}")
        
        return ruta_csv, ruta_json
        
    except Exception as e:
        print(f"⚠️  Error creando resumen general: {e}")
        return None, None

# ======================================================
# 6. FUNCIÓN PARA GRAFICAR PRONÓSTICO CON MANEJO DE FECHAS
# ======================================================
def graficar_pronostico(modelo, serie, variable, pasos=48, limite=None):
    try:
        pred = modelo.get_forecast(steps=pasos)
        media = pred.predicted_mean
        conf_80 = pred.conf_int(alpha=0.20)
        conf_95 = pred.conf_int(alpha=0.05)

        # Crear figura con tamaño adecuado
        fig, ax = plt.subplots(figsize=(15, 6))

        # Datos históricos
        ax.plot(serie.index, serie.values, label="Medido", color="black", linewidth=1.5)

        # Verificar si el pronóstico tiene índice de fechas
        if hasattr(media.index, 'freq') and media.index.freq is not None:
            # El pronóstico tiene fechas
            fecha_min = serie.index.min()
            fecha_max = media.index.max()
            
            # Pronóstico
            ax.plot(
                media.index,
                media.values,
                label=f"Pronóstico {variable}",
                color="red",
                linewidth=2,
            )

            # Bandas de confianza
            ax.fill_between(
                conf_80.index,
                conf_80.iloc[:, 0],
                conf_80.iloc[:, 1],
                color="green",
                alpha=0.3,
                label="Confianza 80%",
            )
            ax.fill_between(
                conf_95.index,
                conf_95.iloc[:, 0],
                conf_95.iloc[:, 1],
                color="yellow",
                alpha=0.2,
                label="Confianza 95%",
            )

            # Línea vertical para separar historial de pronóstico
            ultimo_historial = serie.index[-1]
            ax.axvline(x=ultimo_historial, color="gray", linestyle="--", alpha=0.7, linewidth=1)

            # Configurar formato de fechas
            # Calcular diferencia de días para determinar el formato
            dias_totales = (fecha_max - fecha_min).days

            if dias_totales <= 7:  # Si es menos de una semana
                # Formato: Día Hora (ej: "11 Nov 10:00")
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b %H:%M"))
                ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))
            elif dias_totales <= 30:  # Si es menos de un mes
                # Formato: Día Mes (ej: "11 Nov")
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
                ax.xaxis.set_major_locator(mdates.DayLocator(interval=2))
            else:  # Si es más de un mes
                # Formato: Mes (ej: "Nov 2025")
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
                ax.xaxis.set_major_locator(mdates.MonthLocator())

            # Agregar leyenda de separación
            ax.text(
                ultimo_historial + timedelta(hours=1),
                ax.get_ylim()[1] * 0.95,
                "Pronóstico",
                fontsize=10,
                color="darkred",
                alpha=0.8,
            )
        else:
            # El pronóstico no tiene fechas, usar índice numérico
            print(f"⚠️  Pronóstico para {variable} no tiene fechas, usando índice numérico")
            
            # Crear fechas para el pronóstico
            ultima_fecha = serie.index[-1]
            frec = pd.infer_freq(serie.index) or 'H'
            fechas_pronostico = pd.date_range(
                start=ultima_fecha + pd.Timedelta(hours=1), 
                periods=pasos, 
                freq=frec
            )
            
            # Pronóstico
            ax.plot(
                fechas_pronostico,
                media.values,
                label=f"Pronóstico {variable}",
                color="red",
                linewidth=2,
            )

            # Línea vertical para separar historial de pronóstico
            ax.axvline(x=ultima_fecha, color="gray", linestyle="--", alpha=0.7, linewidth=1)

            # Formato de fechas para todo el gráfico
            todas_fechas = list(serie.index) + list(fechas_pronostico)
            fecha_min = min(todas_fechas)
            fecha_max = max(todas_fechas)
            
            dias_totales = (fecha_max - fecha_min).days
            
            if dias_totales <= 7:
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b %H:%M"))
                ax.xaxis.set_major_locator(mdates.HourLocator(interval=6))
            elif dias_totales <= 30:
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%d %b"))
                ax.xaxis.set_major_locator(mdates.DayLocator(interval=2))
            else:
                ax.xaxis.set_major_formatter(mdates.DateFormatter("%b %Y"))
                ax.xaxis.set_major_locator(mdates.MonthLocator())

        # Línea de norma o límite permitido
        if limite is not None:
            ax.axhline(
                y=limite,
                color="blue",
                linestyle="--",
                linewidth=2,
                label="Nivel máximo permitido (24H) en Colombia",
            )

        # Rotar etiquetas para mejor lectura
        plt.setp(ax.xaxis.get_majorticklabels(), rotation=45, ha="right")

        # Títulos y etiquetas
        ax.set_title(f"Pronóstico SARIMA - {variable}", fontsize=14, fontweight="bold")
        ax.set_xlabel("Fecha y Hora", fontsize=12)

        # Etiqueta del eje Y dependiendo de la variable
        if variable == "Temperature":
            ax.set_ylabel("Temperatura (°C)", fontsize=12)
        elif variable == "Humidity":
            ax.set_ylabel("Humedad (%)", fontsize=12)
        elif variable in ["PM 2.5", "PM 10"]:
            ax.set_ylabel(f"{variable} (µg/m³)", fontsize=12)
        else:
            ax.set_ylabel(variable, fontsize=12)

        # Cuadrícula
        ax.grid(True, alpha=0.3, linestyle="--")

        # Leyenda
        ax.legend(loc="upper left", fontsize=10)

        # Ajustar márgenes
        plt.tight_layout()
        
        return fig
        
    except Exception as e:
        print(f"⚠️  Error al graficar pronóstico para {variable}: {e}")
        return None

# ======================================================
# 7. EJECUCIÓN COMPLETA POR VARIABLE CON MANEJO DE ERRORES
# ======================================================
limites = {
    "Temperature": None,
    "Humidity": None,
    "PM 2.5": 37,  # valor OMS o Colombia
    "PM 10": 75,
}

resultados = {}
ecuaciones = {}
archivos_guardados = []

print(f"\n{'='*80}")
print("🚀 INICIANDO PROCESO DE MODELADO SARIMA")
print(f"{'='*80}")

for var in variables:
    print(f"\n{'='*80}")
    print(f" OPTIMIZANDO: {var}")
    print(f"{'='*80}")

    serie = df_hourly[var]

    try:
        modelo, orden, orden_s, aic, parametros, summary = buscar_mejor_modelo(serie)

        print(f"\nMejor modelo para {var}: SARIMA{orden}{orden_s}")
        print(f"AIC = {aic:.2f}")

        # Obtener y mostrar ecuación matemática
        try:
            ecuacion = obtener_ecuacion_sarima(modelo, orden, orden_s)
            print(f"\nEcuación matemática:")
            print(f"{ecuacion}")
        except Exception as e:
            print(f"⚠️  Error obteniendo ecuación: {e}")
            ecuacion = "No disponible"

        # Mostrar parámetros en formato de tabla
        try:
            mostrar_parametros_tabla(modelo, orden, orden_s, aic)
        except Exception as e:
            print(f"⚠️  Error mostrando parámetros: {e}")

        # Guardar resultados en diccionarios
        resultados[var] = modelo
        ecuaciones[var] = ecuacion

        # Graficar pronóstico (72 horas adelante)
        try:
            fig = graficar_pronostico(modelo, serie, var, pasos=72, limite=limites[var])
            if fig is not None:
                # Guardar gráfico
                ruta_grafico = guardar_grafico_pronostico(fig, var)
                if ruta_grafico:
                    archivos_guardados.append(("Gráfico", var, ruta_grafico))
                plt.close(fig)
        except Exception as e:
            print(f"⚠️  Error graficando pronóstico: {e}")
        
        # Guardar pronóstico en CSV
        try:
            ruta_csv = guardar_pronostico_csv(modelo, serie, var, pasos=72)
            if ruta_csv:
                archivos_guardados.append(("CSV", var, ruta_csv))
        except Exception as e:
            print(f"⚠️  Error guardando CSV para {var}: {e}")
        
        # Guardar parámetros en JSON (archivo pequeño)
        try:
            ruta_json = guardar_parametros_json(modelo, var, orden, orden_s, aic, ecuacion)
            if ruta_json:
                archivos_guardados.append(("JSON Parámetros", var, ruta_json))
        except Exception as e:
            print(f"⚠️  Error guardando parámetros JSON para {var}: {e}")
            
    except Exception as e:
        print(f"❌ Error procesando {var}: {e}")
        print(f"⚠️  Saltando variable {var}...")

# ======================================================
# 8. CREAR RESUMEN GENERAL
# ======================================================
try:
    ruta_csv_resumen, ruta_json_resumen = crear_resumen_general(resultados, ecuaciones, df_hourly, variables)
    if ruta_csv_resumen:
        archivos_guardados.append(("Resumen CSV", "General", ruta_csv_resumen))
    if ruta_json_resumen:
        archivos_guardados.append(("Resumen JSON", "General", ruta_json_resumen))
except Exception as e:
    print(f"⚠️  Error creando resumen general: {e}")

# ======================================================
# 9. RESUMEN FINAL DE TODOS LOS MODELOS
# ======================================================
print(f"\n{'='*80}")
print(" 📊 RESUMEN FINAL DE MODELOS SARIMA")
print(f"{'='*80}")

for var in variables:
    if var in resultados:
        print(f"\n{var}:")
        print(f"  Modelo: SARIMA{resultados[var].specification.order}")
        print(f"          {resultados[var].specification.seasonal_order}")
        print(f"  AIC: {resultados[var].aic:.2f}")
        print(f"  Ecuación: {ecuaciones.get(var, 'No disponible')}")
        print(f"  Número de observaciones: {len(df_hourly[var])}")
        print(f"  Último dato: {df_hourly[var].iloc[-1]:.2f} ({df_hourly.index[-1].strftime('%Y-%m-%d %H:%M')})")
    else:
        print(f"\n{var}: No se pudo ajustar modelo")

# ======================================================
# 10. RESUMEN DE ARCHIVOS GUARDADOS
# ======================================================
print(f"\n{'='*80}")
print(" 💾 ARCHIVOS GUARDADOS")
print(f"{'='*80}")

if archivos_guardados:
    for tipo, variable, ruta in archivos_guardados:
        print(f"  {tipo} - {variable}: {ruta}")
    
    # Contar por tipo
    tipos_contador = {}
    for tipo, _, _ in archivos_guardados:
        tipos_contador[tipo] = tipos_contador.get(tipo, 0) + 1
    
    print(f"\n📊 Total de archivos guardados: {len(archivos_guardados)}")
    for tipo, count in tipos_contador.items():
        print(f"  {tipo}: {count} archivo(s)")
else:
    print("  No se guardaron archivos.")

print(f"\n{'='*80}")
print(" ✅ PROCESO COMPLETADO EXITOSAMENTE")
print(f"{'='*80}")

# Mostrar ubicación de las carpetas
if carpetas:
    print(f"\n📁 Carpetas creadas:")
    for nombre, ruta in carpetas.items():
        print(f"  {nombre}: {ruta}")
        
    # Verificar contenido
    print(f"\n📋 Contenido de las carpetas:")
    for nombre, ruta in carpetas.items():
        if os.path.exists(ruta):
            archivos = os.listdir(ruta)
            if archivos:
                print(f"  {nombre} ({len(archivos)} archivos):")
                for archivo in archivos[:5]:  # Mostrar solo primeros 5
                    tamaño = os.path.getsize(os.path.join(ruta, archivo))
                    tamaño_mb = tamaño / (1024 * 1024)
                    print(f"    - {archivo} ({tamaño_mb:.2f} MB)")
                if len(archivos) > 5:
                    print(f"    ... y {len(archivos) - 5} más")
            else:
                print(f"  {nombre}: vacía")
else:
    print("⚠️  No se pudieron crear carpetas para guardar resultados")

# ======================================================
# 11. LIMPIAR ARCHIVOS TEMPORALES GRANDES
# ======================================================
print(f"\n{'='*80}")
print(" 🧹 LIMPIANDO ARCHIVOS TEMPORALES")
print("=" * 80)

# Listar archivos temporales grandes y eliminarlos si existen
archivos_a_eliminar = []
for root, dirs, files in os.walk('.'):
    for file in files:
        if file.endswith('.pkl'):
            ruta_completa = os.path.join(root, file)
            archivos_a_eliminar.append(ruta_completa)

if archivos_a_eliminar:
    print(f"⚠️  Encontrados {len(archivos_a_eliminar)} archivos .pkl grandes:")
    for archivo in archivos_a_eliminar:
        try:
            tamaño = os.path.getsize(archivo)
            tamaño_mb = tamaño / (1024 * 1024)
            print(f"  - {archivo} ({tamaño_mb:.2f} MB)")
            
            # Preguntar si eliminar (en modo interactivo)
            # En GitHub Actions, eliminamos automáticamente
            if not IN_COLAB:
                os.remove(archivo)
                print(f"    ✅ Eliminado")
        except:
            pass
    print("✅ Archivos temporales grandes eliminados para evitar problemas con GitHub")
else:
    print("✅ No se encontraron archivos .pkl grandes")
